
name: Build push and deploy

on:
  push:
    branches:
      - main

jobs:
  build_push:
      name: Build and Push
      runs-on: ubuntu-latest
      steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: maxrsb/nano-flow:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
  
      - name: Write kubeconfig to ~/.kube/config
        run: |
          mkdir ~/.kube
          echo '${{ secrets.KUBE_CONFIG }}' > ~/.kube/config

      - name: Terraform init, validate, plan and apply
        run: |
          cd terraform
          echo "** Running Terraform Init**"
          terraform init

          echo "** Running Terraform Apply**"
          terraform apply -auto-approve -var="image_tag=${{ github.sha }}"